version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout

      - run:
          name: Install libralies for API
          working_directory: ./API
          command: npm install

      - run:
          name: API Unit Test
          working_directory: ./API
          command: npm test

      - run:
          name: Install serverless
          working_directory: ~/
          command: sudo npm install -g serverless

      - run:
          # ＜ Circle CI の設定 ＞
          # CircleCIの BUILDS>PROJECTS>Settings>Environment Variables画面より、
          # AWS_ACCESS_KEY と AWS_SECRET_KEY を設定してください。
          #
          name: Deploy Test
          working_directory: ./API
          command: |
            sls config credentials -k ${AWS_ACCESS_KEY} -s ${AWS_SECRET_KEY} -p aws
            
            # CircleCIのテストとしてdeployを通過させるため listにしています。
            sls deploy list
            # sls deploy

      - run:
          name: Run e2e Test
          working_directory: ./API
          command: npm run e2e

