version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout

      - run:
          name: Install libralies for API
          working_directory: ./API
          command: npm install

      - run:
          name: Run API Unit Test
          working_directory: ./API
          command: npm test

      - run:
          # ＜ Circle CI の設定 ＞
          # CircleCIの BUILDS>PROJECTS>Settings>Environment Variables画面より、
          # AWS_ACCESS_KEY と AWS_SECRET_KEY を設定してください。

          # TODO master ブランチかどうか判定してから実行する必要があるか？
          name: Deploy API & e2e Test
          working_directory: ./API
          command: |
            if [ "${CIRCLE_BRANCH}" == "master2" ]; then
              sudo npm install -g serverless
              sls config credentials -k ${AWS_ACCESS_KEY} -s ${AWS_SECRET_KEY} -p aws
              sls deploy
              npm run e2e
            fi

# git add . ; git commit -m "CircleCI2.0のテストです。"; git push