version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - run:
          command: cd API && npm install
      - run:
          command: cd API && npm test
