version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - run:
          working_directory: API
          command: npm install
      - run:
          working_directory: API
          command: npm test
      - run:
          working_directory: .
          command: |
            npm install
      - run:
          command: serverless deploy list
